import asyncio
import os
import secrets
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from aiohttp import web
from aiogram import Bot, Dispatcher, F
from aiogram.client.session.aiohttp import AiohttpSession
from aiogram.filters import Command
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from aiogram.types import (
    Message,
    CallbackQuery,
    InlineKeyboardMarkup,
    InlineKeyboardButton,
)
from aiogram.webhook.aiohttp_server import SimpleRequestHandler, setup_application
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()

LOCAL_MODE = os.getenv("LOCAL_MODE", "false").lower() == "true"

BOT_TOKEN = os.environ["BOT_TOKEN"]
CHAT_ID = int(os.environ["CHAT_ID"])
WEBHOOK_BASE_URL = os.getenv("WEBHOOK_BASE_URL", "").rstrip("/")
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "local-secret")
SCHEDULER_KEY = os.getenv("SCHEDULER_KEY", "local-scheduler-key")
BOT_PROXY = os.getenv("BOT_PROXY")

TIMEZONE = os.getenv("TIMEZONE", "Europe/Moscow")
TZ = ZoneInfo(TIMEZONE)

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///cleaning.db")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

DEFAULT_BATHROOM_INTERVAL_DAYS = int(os.getenv("BATHROOM_INTERVAL_DAYS", "14"))

FRIDAY_ANNOUNCE_START_HOUR = int(os.getenv("FRIDAY_ANNOUNCE_START_HOUR", "17"))
FRIDAY_ANNOUNCE_END_HOUR = int(os.getenv("FRIDAY_ANNOUNCE_END_HOUR", "20"))

SATURDAY_REMINDER_START_HOUR = int(os.getenv("SATURDAY_REMINDER_START_HOUR", "10"))
SATURDAY_REMINDER_END_HOUR = int(os.getenv("SATURDAY_REMINDER_END_HOUR", "12"))

SUNDAY_REMINDER_START_HOUR = int(os.getenv("SUNDAY_REMINDER_START_HOUR", "11"))
SUNDAY_REMINDER_END_HOUR = int(os.getenv("SUNDAY_REMINDER_END_HOUR", "13"))

SUNDAY_FINAL_START_HOUR = int(os.getenv("SUNDAY_FINAL_START_HOUR", "17"))
SUNDAY_FINAL_END_HOUR = int(os.getenv("SUNDAY_FINAL_END_HOUR", "20"))

MEMBERS = []
for key in ("USER_1", "USER_2", "USER_3"):
    raw = os.environ[key]
    user_id, name = raw.split("|", 1)
    MEMBERS.append({"id": int(user_id), "name": name.strip()})

MEMBERS_BY_ID = {member["id"]: member for member in MEMBERS}

CHORES = {
    "floor": {"title": "мытьё пола", "short": "Пол", "emoji": "🧹"},
    "bathroom": {"title": "уборка ванной", "short": "Ванная", "emoji": "🛁"},
}

engine = create_engine(DATABASE_URL, pool_pre_ping=True)

session = AiohttpSession(proxy=BOT_PROXY) if BOT_PROXY else AiohttpSession()
bot = Bot(BOT_TOKEN, session=session)
dp = Dispatcher()


class SetupQueue(StatesGroup):
    choosing_first = State()
    choosing_second = State()


class BathroomInterval(StatesGroup):
    waiting_custom_days = State()


def init_db():
    ddl = [
        """
        CREATE TABLE IF NOT EXISTS chore_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chore VARCHAR(32) NOT NULL,
            user_id BIGINT NOT NULL,
            user_name VARCHAR(255) NOT NULL,
            event_type VARCHAR(32) NOT NULL,
            created_at VARCHAR(64) NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS weekly_tasks (
            iso_year INTEGER NOT NULL,
            iso_week INTEGER NOT NULL,
            chore VARCHAR(32) NOT NULL,
            user_id BIGINT NOT NULL,
            user_name VARCHAR(255) NOT NULL,
            status VARCHAR(32) NOT NULL DEFAULT 'pending',
            PRIMARY KEY (iso_year, iso_week, chore)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS sent_notifications (
            notification_key VARCHAR(128) PRIMARY KEY,
            sent_at VARCHAR(64) NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS chore_queue (
            chore VARCHAR(32) NOT NULL,
            position INTEGER NOT NULL,
            user_id BIGINT NOT NULL,
            user_name VARCHAR(255) NOT NULL,
            PRIMARY KEY (chore, position)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS bot_settings (
            setting_key VARCHAR(128) PRIMARY KEY,
            setting_value VARCHAR(255) NOT NULL
        )
        """,
    ]

    if DATABASE_URL.startswith("sqlite"):
        ddl[0] = """
        CREATE TABLE IF NOT EXISTS chore_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            chore VARCHAR(32) NOT NULL,
            user_id BIGINT NOT NULL,
            user_name VARCHAR(255) NOT NULL,
            event_type VARCHAR(32) NOT NULL,
            created_at VARCHAR(64) NOT NULL
        )
        """

    with engine.begin() as conn:
        for statement in ddl:
            conn.execute(text(statement))

        for chore in CHORES:
            count = conn.execute(
                text("SELECT COUNT(*) FROM chore_queue WHERE chore = :chore"),
                {"chore": chore},
            ).scalar_one()
            if count == 0:
                for position, member in enumerate(MEMBERS):
                    conn.execute(
                        text(
                            """
                            INSERT INTO chore_queue
                            (chore, position, user_id, user_name)
                            VALUES (:chore, :position, :uid, :name)
                            """
                        ),
                        {
                            "chore": chore,
                            "position": position,
                            "uid": member["id"],
                            "name": member["name"],
                        },
                    )

        interval_exists = conn.execute(
            text(
                "SELECT setting_value FROM bot_settings "
                "WHERE setting_key = 'bathroom_interval_days'"
            )
        ).first()
        if not interval_exists:
            conn.execute(
                text(
                    """
                    INSERT INTO bot_settings (setting_key, setting_value)
                    VALUES ('bathroom_interval_days', :value)
                    """
                ),
                {"value": str(DEFAULT_BATHROOM_INTERVAL_DAYS)},
            )


def fetch_one(query, params=None):
    with engine.begin() as conn:
        return conn.execute(text(query), params or {}).mappings().first()


def fetch_all(query, params=None):
    with engine.begin() as conn:
        return list(conn.execute(text(query), params or {}).mappings().all())


def execute(query, params=None):
    with engine.begin() as conn:
        conn.execute(text(query), params or {})


def is_household_member(user_id: int) -> bool:
    return user_id in MEMBERS_BY_ID


def get_setting(key: str, default=None):
    row = fetch_one(
        "SELECT setting_value FROM bot_settings WHERE setting_key = :key",
        {"key": key},
    )
    return row["setting_value"] if row else default


def set_setting(key: str, value: str):
    if DATABASE_URL.startswith("sqlite"):
        execute(
            """
            INSERT INTO bot_settings (setting_key, setting_value)
            VALUES (:key, :value)
            ON CONFLICT(setting_key) DO UPDATE SET setting_value = excluded.setting_value
            """,
            {"key": key, "value": value},
        )
    else:
        execute(
            """
            INSERT INTO bot_settings (setting_key, setting_value)
            VALUES (:key, :value)
            ON CONFLICT (setting_key)
            DO UPDATE SET setting_value = EXCLUDED.setting_value
            """,
            {"key": key, "value": value},
        )


def get_bathroom_interval_days() -> int:
    return int(get_setting("bathroom_interval_days", str(DEFAULT_BATHROOM_INTERVAL_DAYS)))


def get_queue(chore: str):
    rows = fetch_all(
        """
        SELECT user_id, user_name
        FROM chore_queue
        WHERE chore = :chore
        ORDER BY position
        """,
        {"chore": chore},
    )
    return [{"id": int(row["user_id"]), "name": row["user_name"]} for row in rows]


def set_queue(chore: str, ordered_members):
    with engine.begin() as conn:
        conn.execute(text("DELETE FROM chore_queue WHERE chore = :chore"), {"chore": chore})
        for position, member in enumerate(ordered_members):
            conn.execute(
                text(
                    """
                    INSERT INTO chore_queue
                    (chore, position, user_id, user_name)
                    VALUES (:chore, :position, :uid, :name)
                    """
                ),
                {
                    "chore": chore,
                    "position": position,
                    "uid": member["id"],
                    "name": member["name"],
                },
            )


def get_queue_member(chore: str):
    return get_queue(chore)[0]


def advance_turn(chore: str):
    queue = get_queue(chore)
    set_queue(chore, queue[1:] + queue[:1])


def reset_current_week_task(chore: str):
    year, week = week_now()
    execute(
        """
        DELETE FROM weekly_tasks
        WHERE iso_year = :year AND iso_week = :week AND chore = :chore
        """,
        {"year": year, "week": week, "chore": chore},
    )


def record_event(chore: str, member, event_type: str):
    execute(
        """
        INSERT INTO chore_events
        (chore, user_id, user_name, event_type, created_at)
        VALUES (:chore, :uid, :name, :event_type, :created_at)
        """,
        {
            "chore": chore,
            "uid": member["id"],
            "name": member["name"],
            "event_type": event_type,
            "created_at": datetime.now(TZ).isoformat(),
        },
    )


def get_last_bathroom_done():
    row = fetch_one(
        """
        SELECT created_at
        FROM chore_events
        WHERE chore = 'bathroom' AND event_type = 'done'
        ORDER BY id DESC
        LIMIT 1
        """
    )
    if not row:
        return None
    return datetime.fromisoformat(row["created_at"]).astimezone(TZ)


def bathroom_due() -> bool:
    last_done = get_last_bathroom_done()
    if last_done is None:
        return True
    return datetime.now(TZ) >= last_done + timedelta(days=get_bathroom_interval_days())


def next_bathroom_due_at():
    last_done = get_last_bathroom_done()
    if last_done is None:
        return None
    return last_done + timedelta(days=get_bathroom_interval_days())


def chore_due(chore: str) -> bool:
    return chore == "floor" or (chore == "bathroom" and bathroom_due())


def week_now():
    iso = datetime.now(TZ).isocalendar()
    return iso.year, iso.week


def get_or_create_weekly_task(chore: str, iso_year: int, iso_week: int):
    if not chore_due(chore):
        return None

    row = fetch_one(
        """
        SELECT user_id, user_name, status
        FROM weekly_tasks
        WHERE iso_year = :year AND iso_week = :week AND chore = :chore
        """,
        {"year": iso_year, "week": iso_week, "chore": chore},
    )
    if row:
        return {
            "id": int(row["user_id"]),
            "name": row["user_name"],
            "status": row["status"],
        }

    member = get_queue_member(chore)
    execute(
        """
        INSERT INTO weekly_tasks
        (iso_year, iso_week, chore, user_id, user_name, status)
        VALUES (:year, :week, :chore, :uid, :name, 'pending')
        """,
        {
            "year": iso_year,
            "week": iso_week,
            "chore": chore,
            "uid": member["id"],
            "name": member["name"],
        },
    )
    return {**member, "status": "pending"}


def set_weekly_done(chore: str, iso_year: int, iso_week: int):
    execute(
        """
        UPDATE weekly_tasks SET status = 'done'
        WHERE iso_year = :year AND iso_week = :week AND chore = :chore
        """,
        {"year": iso_year, "week": iso_week, "chore": chore},
    )


def reassign_weekly_task(chore: str, iso_year: int, iso_week: int, member):
    execute(
        """
        UPDATE weekly_tasks
        SET user_id = :uid, user_name = :name, status = 'pending'
        WHERE iso_year = :year AND iso_week = :week AND chore = :chore
        """,
        {
            "uid": member["id"],
            "name": member["name"],
            "year": iso_year,
            "week": iso_week,
            "chore": chore,
        },
    )


def notification_already_sent(key: str) -> bool:
    return fetch_one(
        "SELECT notification_key FROM sent_notifications WHERE notification_key = :key",
        {"key": key},
    ) is not None


def mark_notification_sent(key: str):
    if DATABASE_URL.startswith("sqlite"):
        execute(
            """
            INSERT OR IGNORE INTO sent_notifications (notification_key, sent_at)
            VALUES (:key, :sent_at)
            """,
            {"key": key, "sent_at": datetime.now(TZ).isoformat()},
        )
    else:
        execute(
            """
            INSERT INTO sent_notifications (notification_key, sent_at)
            VALUES (:key, :sent_at)
            ON CONFLICT (notification_key) DO NOTHING
            """,
            {"key": key, "sent_at": datetime.now(TZ).isoformat()},
        )


def mention(member):
    return f'<a href="tg://user?id={member["id"]}">{member["name"]}</a>'


def format_queue(chore: str):
    queue = get_queue(chore)
    return " → ".join(member["name"] for member in queue) + " → …"


def chore_keyboard(chore: str, member_id: int):
    return InlineKeyboardMarkup(
        inline_keyboard=[
            [InlineKeyboardButton(text="✅ Сделано", callback_data=f"done:{chore}:{member_id}")],
            [InlineKeyboardButton(text="⏭️ Пропускаю очередь", callback_data=f"skip:{chore}:{member_id}")],
        ]
    )



def manual_done_keyboard():
    return InlineKeyboardMarkup(
        inline_keyboard=[
            [
                InlineKeyboardButton(
                    text="🧹 Пол",
                    callback_data="manual_done:floor",
                ),
                InlineKeyboardButton(
                    text="🛁 Ванная",
                    callback_data="manual_done:bathroom",
                ),
            ],
            [
                InlineKeyboardButton(
                    text="❌ Отмена",
                    callback_data="manual_done:cancel",
                )
            ],
        ]
    )


def settings_keyboard():
    return InlineKeyboardMarkup(
        inline_keyboard=[
            [InlineKeyboardButton(text="🧹 Настроить очередь пола", callback_data="settings:queue:floor")],
            [InlineKeyboardButton(text="🛁 Настроить очередь ванной", callback_data="settings:queue:bathroom")],
            [InlineKeyboardButton(text="📅 Интервал ванной", callback_data="settings:bathroom_interval")],
            [InlineKeyboardButton(text="📊 Показать текущие настройки", callback_data="settings:show")],
        ]
    )


def member_choice_keyboard(prefix: str, exclude_id=None):
    rows = []
    for member in MEMBERS:
        if member["id"] == exclude_id:
            continue
        rows.append([
            InlineKeyboardButton(
                text=member["name"],
                callback_data=f"{prefix}:{member['id']}"
            )
        ])
    rows.append([InlineKeyboardButton(text="❌ Отмена", callback_data="settings:cancel")])
    return InlineKeyboardMarkup(inline_keyboard=rows)


def interval_keyboard():
    return InlineKeyboardMarkup(
        inline_keyboard=[
            [
                InlineKeyboardButton(text="7 дней", callback_data="interval:7"),
                InlineKeyboardButton(text="10 дней", callback_data="interval:10"),
                InlineKeyboardButton(text="14 дней", callback_data="interval:14"),
            ],
            [
                InlineKeyboardButton(text="21 день", callback_data="interval:21"),
                InlineKeyboardButton(text="30 дней", callback_data="interval:30"),
            ],
            [InlineKeyboardButton(text="✏️ Свой интервал", callback_data="interval:custom")],
            [InlineKeyboardButton(text="❌ Отмена", callback_data="settings:cancel")],
        ]
    )


async def deny_if_not_member(event):
    user_id = event.from_user.id
    if is_household_member(user_id):
        return False
    if isinstance(event, CallbackQuery):
        await event.answer("Настройки доступны только участникам квартиры.", show_alert=True)
    else:
        await event.answer("Настройки доступны только участникам квартиры.")
    return True



def manual_complete_chore(chore: str, user_id: int):
    if chore not in CHORES:
        return False, "Неизвестная задача.", None

    queue_member = get_queue_member(chore)

    if queue_member["id"] != user_id:
        return (
            False,
            f"Сейчас очередь: {queue_member['name']}. "
            "Отметить выполнение может только текущий дежурный.",
            None,
        )

    iso_year, iso_week = week_now()

    if chore == "floor":
        row = fetch_one(
            """
            SELECT user_id, user_name, status
            FROM weekly_tasks
            WHERE iso_year = :year AND iso_week = :week AND chore = 'floor'
            """,
            {"year": iso_year, "week": iso_week},
        )

        if row and row["status"] == "done":
            return False, "Пол на этой неделе уже отмечен как выполненный.", None

        if row:
            execute(
                """
                UPDATE weekly_tasks
                SET user_id = :uid, user_name = :name, status = 'done'
                WHERE iso_year = :year AND iso_week = :week AND chore = 'floor'
                """,
                {
                    "uid": queue_member["id"],
                    "name": queue_member["name"],
                    "year": iso_year,
                    "week": iso_week,
                },
            )
        else:
            execute(
                """
                INSERT INTO weekly_tasks
                (iso_year, iso_week, chore, user_id, user_name, status)
                VALUES (:year, :week, 'floor', :uid, :name, 'done')
                """,
                {
                    "year": iso_year,
                    "week": iso_week,
                    "uid": queue_member["id"],
                    "name": queue_member["name"],
                },
            )

    else:
        row = fetch_one(
            """
            SELECT status
            FROM weekly_tasks
            WHERE iso_year = :year AND iso_week = :week AND chore = 'bathroom'
            """,
            {"year": iso_year, "week": iso_week},
        )

        if row and row["status"] == "done":
            return False, "Ванная на этой неделе уже отмечена как выполненная.", None

        if row:
            execute(
                """
                UPDATE weekly_tasks
                SET user_id = :uid, user_name = :name, status = 'done'
                WHERE iso_year = :year AND iso_week = :week AND chore = 'bathroom'
                """,
                {
                    "uid": queue_member["id"],
                    "name": queue_member["name"],
                    "year": iso_year,
                    "week": iso_week,
                },
            )

    record_event(chore, queue_member, "done")
    advance_turn(chore)
    next_member = get_queue_member(chore)

    return True, None, next_member


async def send_chore_message(chore: str, prefix: str, iso_year: int, iso_week: int):
    task = get_or_create_weekly_task(chore, iso_year, iso_week)
    if not task or task["status"] == "done":
        return False

    data = CHORES[chore]
    await bot.send_message(
        CHAT_ID,
        (
            f"{prefix}\n\n"
            f"{data['emoji']} <b>{data['title'].capitalize()}</b>\n"
            f"Дежурит: {mention(task)}\n\n"
            "Когда закончишь — нажми «✅ Сделано»."
        ),
        reply_markup=chore_keyboard(chore, task["id"]),
        parse_mode="HTML",
    )
    return True


@dp.message(Command("start"))
async def start_cmd(message: Message):
    await message.answer(
        "Привет! Я слежу за уборкой.\n\n"
        "/status — текущие очереди\n"
        "/history — история\n"
        "/settings — настроить очереди и ванную\n"
        "/done — отметить уборку вручную\n"
        "/test — прислать тестовые задачи"
    )


@dp.message(Command("settings"))
async def settings_cmd(message: Message, state: FSMContext):
    if await deny_if_not_member(message):
        return
    await state.clear()
    await message.answer("⚙️ <b>Настройки уборки</b>", reply_markup=settings_keyboard(), parse_mode="HTML")


@dp.callback_query(F.data == "settings:show")
async def settings_show(callback: CallbackQuery):
    if await deny_if_not_member(callback):
        return
    interval = get_bathroom_interval_days()
    next_due = next_bathroom_due_at()
    due_text = "уже пора" if bathroom_due() else f"после {next_due:%d.%m.%Y}"
    await callback.answer()
    await callback.message.answer(
        "⚙️ <b>Текущие настройки</b>\n\n"
        f"🧹 Пол: {format_queue('floor')}\n"
        f"🛁 Ванная: {format_queue('bathroom')}\n"
        f"📅 Интервал ванной: {interval} дн.\n"
        f"⏰ Следующая ванная: {due_text}",
        parse_mode="HTML",
    )


@dp.callback_query(F.data.startswith("settings:queue:"))
async def settings_queue_start(callback: CallbackQuery, state: FSMContext):
    if await deny_if_not_member(callback):
        return
    chore = callback.data.split(":", 2)[2]
    if chore not in CHORES:
        await callback.answer("Неизвестная задача.", show_alert=True)
        return

    await state.clear()
    await state.set_state(SetupQueue.choosing_first)
    await state.update_data(chore=chore)
    await callback.answer()
    await callback.message.answer(
        f"{CHORES[chore]['emoji']} Настраиваем: <b>{CHORES[chore]['short']}</b>\n\n"
        "Кто должен быть <b>первым</b> — то есть дежурить сейчас/в ближайшую уборку?",
        reply_markup=member_choice_keyboard(f"queue_first:{chore}"),
        parse_mode="HTML",
    )


@dp.callback_query(SetupQueue.choosing_first, F.data.startswith("queue_first:"))
async def settings_queue_first(callback: CallbackQuery, state: FSMContext):
    if await deny_if_not_member(callback):
        return
    _, chore, user_id_raw = callback.data.split(":", 2)
    first_id = int(user_id_raw)
    first = MEMBERS_BY_ID.get(first_id)
    if not first:
        await callback.answer("Неизвестный пользователь.", show_alert=True)
        return

    await state.update_data(chore=chore, first_id=first_id)
    await state.set_state(SetupQueue.choosing_second)
    await callback.answer()
    await callback.message.answer(
        f"Первый: <b>{first['name']}</b>.\n\nКто должен идти <b>вторым</b>?",
        reply_markup=member_choice_keyboard(f"queue_second:{chore}", exclude_id=first_id),
        parse_mode="HTML",
    )


@dp.callback_query(SetupQueue.choosing_second, F.data.startswith("queue_second:"))
async def settings_queue_second(callback: CallbackQuery, state: FSMContext):
    if await deny_if_not_member(callback):
        return
    _, chore, user_id_raw = callback.data.split(":", 2)
    second_id = int(user_id_raw)
    data = await state.get_data()
    first_id = int(data["first_id"])

    if second_id == first_id or second_id not in MEMBERS_BY_ID:
        await callback.answer("Выбери другого участника.", show_alert=True)
        return

    third_id = next(member["id"] for member in MEMBERS if member["id"] not in (first_id, second_id))
    ordered = [MEMBERS_BY_ID[first_id], MEMBERS_BY_ID[second_id], MEMBERS_BY_ID[third_id]]
    set_queue(chore, ordered)
    reset_current_week_task(chore)
    await state.clear()

    await callback.answer("Очередь сохранена!")
    await callback.message.answer(
        f"✅ Очередь для <b>{CHORES[chore]['short'].lower()}</b> сохранена:\n\n"
        f"1. {ordered[0]['name']}\n"
        f"2. {ordered[1]['name']}\n"
        f"3. {ordered[2]['name']}\n\n"
        "После выполнения она будет крутиться по кругу.",
        reply_markup=settings_keyboard(),
        parse_mode="HTML",
    )


@dp.callback_query(F.data == "settings:bathroom_interval")
async def bathroom_interval_menu(callback: CallbackQuery, state: FSMContext):
    if await deny_if_not_member(callback):
        return
    await state.clear()
    current = get_bathroom_interval_days()
    await callback.answer()
    await callback.message.answer(
        f"🛁 Сейчас ванная становится актуальной через <b>{current} дней</b> после последней уборки.\n\n"
        "Выбери новый интервал:",
        reply_markup=interval_keyboard(),
        parse_mode="HTML",
    )


@dp.callback_query(F.data.startswith("interval:"))
async def bathroom_interval_callback(callback: CallbackQuery, state: FSMContext):
    if await deny_if_not_member(callback):
        return
    value = callback.data.split(":", 1)[1]
    if value == "custom":
        await state.set_state(BathroomInterval.waiting_custom_days)
        await callback.answer()
        await callback.message.answer("Напиши одним числом, через сколько дней снова мыть ванную. Например: <b>17</b>", parse_mode="HTML")
        return

    days = int(value)
    set_setting("bathroom_interval_days", str(days))
    await state.clear()
    await callback.answer("Сохранено!")
    await callback.message.answer(
        f"✅ Интервал ванной теперь <b>{days} дней</b>.",
        reply_markup=settings_keyboard(),
        parse_mode="HTML",
    )


@dp.message(BathroomInterval.waiting_custom_days)
async def bathroom_interval_custom(message: Message, state: FSMContext):
    if await deny_if_not_member(message):
        return
    try:
        days = int(message.text.strip())
    except (ValueError, AttributeError):
        await message.answer("Нужно прислать одно целое число, например <b>17</b>.", parse_mode="HTML")
        return

    if not 1 <= days <= 365:
        await message.answer("Давай число от 1 до 365 дней 🙂")
        return

    set_setting("bathroom_interval_days", str(days))
    await state.clear()
    next_due = next_bathroom_due_at()
    extra = ""
    if next_due:
        extra = f"\nПо последней уборке следующая дата: <b>{next_due:%d.%m.%Y}</b>."
    await message.answer(
        f"✅ Интервал ванной теперь <b>{days} дней</b>.{extra}",
        reply_markup=settings_keyboard(),
        parse_mode="HTML",
    )


@dp.callback_query(F.data == "settings:cancel")
async def settings_cancel(callback: CallbackQuery, state: FSMContext):
    await state.clear()
    await callback.answer("Отменено")
    await callback.message.answer("⚙️ Настройки", reply_markup=settings_keyboard())


@dp.message(Command("setup_floor"))
async def setup_floor_cmd(message: Message, state: FSMContext):
    if await deny_if_not_member(message):
        return
    await state.clear()
    await state.set_state(SetupQueue.choosing_first)
    await state.update_data(chore="floor")
    await message.answer(
        "🧹 Кто моет пол первым?",
        reply_markup=member_choice_keyboard("queue_first:floor"),
    )


@dp.message(Command("setup_bathroom"))
async def setup_bathroom_cmd(message: Message, state: FSMContext):
    if await deny_if_not_member(message):
        return
    await state.clear()
    await state.set_state(SetupQueue.choosing_first)
    await state.update_data(chore="bathroom")
    await message.answer(
        "🛁 Кто идёт первым по ванной?",
        reply_markup=member_choice_keyboard("queue_first:bathroom"),
    )


@dp.message(Command("bathroom_interval"))
async def bathroom_interval_cmd(message: Message, state: FSMContext):
    if await deny_if_not_member(message):
        return
    parts = message.text.split(maxsplit=1)
    if len(parts) == 2:
        try:
            days = int(parts[1])
        except ValueError:
            await message.answer("Пример: /bathroom_interval 17")
            return
        if not 1 <= days <= 365:
            await message.answer("Интервал должен быть от 1 до 365 дней.")
            return
        set_setting("bathroom_interval_days", str(days))
        await message.answer(f"✅ Интервал ванной: {days} дней.")
        return

    current = get_bathroom_interval_days()
    await state.clear()
    await message.answer(
        f"Сейчас: <b>{current} дней</b>. Выбери новый интервал:",
        reply_markup=interval_keyboard(),
        parse_mode="HTML",
    )



@dp.message(Command("done"))
async def manual_done_cmd(message: Message):
    if await deny_if_not_member(message):
        return

    await message.answer(
        "✅ <b>Что ты уже убрал(а)?</b>\n\n"
        "Отметить выполнение может только тот, чья сейчас очередь.",
        reply_markup=manual_done_keyboard(),
        parse_mode="HTML",
    )


@dp.callback_query(F.data == "manual_done:cancel")
async def manual_done_cancel(callback: CallbackQuery):
    await callback.answer("Отменено")
    await callback.message.edit_reply_markup(reply_markup=None)


@dp.callback_query(F.data.startswith("manual_done:"))
async def manual_done_callback(callback: CallbackQuery):
    if await deny_if_not_member(callback):
        return

    chore = callback.data.split(":", 1)[1]
    if chore not in CHORES:
        return

    ok, error, next_member = manual_complete_chore(
        chore,
        callback.from_user.id,
    )

    if not ok:
        await callback.answer(error, show_alert=True)
        return

    current_member = MEMBERS_BY_ID[callback.from_user.id]
    await callback.answer("Отмечено!")
    await callback.message.edit_reply_markup(reply_markup=None)

    extra = ""
    if chore == "bathroom":
        next_due = next_bathroom_due_at()
        if next_due:
            extra = (
                f"\nСледующая ванная станет актуальной после "
                f"<b>{next_due:%d.%m.%Y}</b>."
            )

    await callback.message.answer(
        f"✅ {mention(current_member)} отметил(а): "
        f"<b>{CHORES[chore]['title']}</b> выполнено.\n"
        f"Следующий в очереди: {mention(next_member)}."
        f"{extra}",
        parse_mode="HTML",
    )


@dp.message(Command("status"))
async def status_cmd(message: Message):
    iso_year, iso_week = week_now()

    floor = get_or_create_weekly_task("floor", iso_year, iso_week)
    floor_text = mention(floor) if floor["status"] == "pending" else "✅ уже выполнено"

    bathroom_task = get_or_create_weekly_task("bathroom", iso_year, iso_week)
    if bathroom_task is None:
        next_due = next_bathroom_due_at()
        bathroom_text = (
            f"пока не пора — после <b>{next_due:%d.%m.%Y}</b>"
            if next_due
            else "пока не задана первая уборка"
        )
    elif bathroom_task["status"] == "done":
        bathroom_text = "✅ уже выполнено"
    else:
        bathroom_text = mention(bathroom_task)

    interval = get_bathroom_interval_days()
    await message.answer(
        f"🧹 <b>Пол:</b> {floor_text}\n"
        f"Очередь: {format_queue('floor')}\n\n"
        f"🛁 <b>Ванная:</b> {bathroom_text}\n"
        f"Очередь: {format_queue('bathroom')}\n"
        f"Интервал: {interval} дн.",
        parse_mode="HTML",
    )


@dp.message(Command("history"))
async def history_cmd(message: Message):
    rows = fetch_all(
        """
        SELECT chore, user_name, event_type, created_at
        FROM chore_events
        ORDER BY id DESC
        LIMIT 15
        """
    )
    if not rows:
        await message.answer("История пока пустая.")
        return

    lines = ["📋 Последние действия:"]
    for row in rows:
        dt = datetime.fromisoformat(row["created_at"]).astimezone(TZ)
        action = "✅ сделано" if row["event_type"] == "done" else "⏭️ пропуск"
        lines.append(f"• {dt:%d.%m}: {CHORES[row['chore']]['title']} — {row['user_name']} — {action}")
    await message.answer("\n".join(lines))


@dp.message(Command("test"))
async def test_cmd(message: Message):
    if await deny_if_not_member(message):
        return
    iso_year, iso_week = week_now()
    await send_chore_message("floor", "🧪 Тестовое напоминание", iso_year, iso_week)
    if bathroom_due():
        await send_chore_message("bathroom", "🧪 Тестовое напоминание", iso_year, iso_week)
    else:
        await message.answer("🧪 Пол отправлен. Ванная пока ещё не подошла по интервалу.")


@dp.callback_query(F.data.startswith("done:"))
async def done_callback(callback: CallbackQuery):
    _, chore, clicked_id_raw = callback.data.split(":", 2)
    clicked_id = int(clicked_id_raw)

    if chore not in CHORES:
        await callback.answer("Неизвестная задача.", show_alert=True)
        return

    iso_year, iso_week = week_now()
    task = get_or_create_weekly_task(chore, iso_year, iso_week)
    if not task or task["status"] == "done":
        await callback.answer("Эта задача уже закрыта.", show_alert=True)
        return

    if callback.from_user.id != clicked_id or task["id"] != clicked_id:
        await callback.answer("Эта кнопка для текущего дежурного 🙂", show_alert=True)
        return

    record_event(chore, task, "done")
    set_weekly_done(chore, iso_year, iso_week)
    advance_turn(chore)
    next_member = get_queue_member(chore)

    extra = ""
    if chore == "bathroom":
        next_due = datetime.now(TZ) + timedelta(days=get_bathroom_interval_days())
        extra = f"\nСледующая ванная станет актуальной после <b>{next_due:%d.%m.%Y}</b>."

    await callback.answer("Отмечено!")
    await callback.message.edit_reply_markup(reply_markup=None)
    await callback.message.answer(
        f"✅ {mention(task)}: {CHORES[chore]['title']} завершено.\n"
        f"Следующий: {mention(next_member)}.{extra}",
        parse_mode="HTML",
    )


@dp.callback_query(F.data.startswith("skip:"))
async def skip_callback(callback: CallbackQuery):
    _, chore, clicked_id_raw = callback.data.split(":", 2)
    clicked_id = int(clicked_id_raw)

    if chore not in CHORES:
        await callback.answer("Неизвестная задача.", show_alert=True)
        return

    iso_year, iso_week = week_now()
    task = get_or_create_weekly_task(chore, iso_year, iso_week)
    if not task or task["status"] == "done":
        await callback.answer("Эта задача уже закрыта.", show_alert=True)
        return

    if callback.from_user.id != clicked_id or task["id"] != clicked_id:
        await callback.answer("Пропустить может только текущий дежурный.", show_alert=True)
        return

    record_event(chore, task, "skip")
    advance_turn(chore)
    next_member = get_queue_member(chore)
    reassign_weekly_task(chore, iso_year, iso_week, next_member)

    await callback.answer("Передано следующему.")
    await callback.message.edit_reply_markup(reply_markup=None)
    await callback.message.answer(
        f"⏭️ {mention(task)} пропускает: {CHORES[chore]['title']}.\n"
        f"Теперь задача у {mention(next_member)}.",
        reply_markup=chore_keyboard(chore, next_member["id"]),
        parse_mode="HTML",
    )


async def health(request):
    return web.json_response({"ok": True, "service": "cleaning-bot"})



def get_current_reminder_window(now: datetime):
    """
    Возвращает активное окно напоминания для текущего локального времени.

    Окна полуоткрытые: start <= hour < end.
    Например 10-12 означает с 10:00 до 11:59.
    """
    weekday = now.weekday()
    hour = now.hour

    windows = [
        (
            4,
            FRIDAY_ANNOUNCE_START_HOUR,
            FRIDAY_ANNOUNCE_END_HOUR,
            "friday",
            "📅 Задачи на эти выходные!",
        ),
        (
            5,
            SATURDAY_REMINDER_START_HOUR,
            SATURDAY_REMINDER_END_HOUR,
            "saturday",
            "☀️ Субботнее напоминание.",
        ),
        (
            6,
            SUNDAY_REMINDER_START_HOUR,
            SUNDAY_REMINDER_END_HOUR,
            "sunday",
            "🧽 Воскресное напоминание.",
        ),
        (
            6,
            SUNDAY_FINAL_START_HOUR,
            SUNDAY_FINAL_END_HOUR,
            "sunday_final",
            "⏰ Последнее напоминание на выходные.",
        ),
    ]

    for target_weekday, start_hour, end_hour, slug, prefix in windows:
        if weekday == target_weekday and start_hour <= hour < end_hour:
            return slug, prefix

    return None

async def scheduler(request):
    provided = request.query.get("key", "")
    if not secrets.compare_digest(provided, SCHEDULER_KEY):
        raise web.HTTPUnauthorized(text="bad scheduler key")

    now = datetime.now(TZ)
    iso = now.isocalendar()
    iso_year, iso_week = iso.year, iso.week

    schedule = get_current_reminder_window(now)
    if not schedule:
        return web.json_response({
            "ok": True,
            "sent": 0,
            "reason": "outside reminder window",
            "local_time": now.isoformat(),
        })

    slug, prefix = schedule
    sent = 0
    for chore in ("floor", "bathroom"):
        if not chore_due(chore):
            continue
        key = f"{iso_year}-W{iso_week}-{slug}-{chore}"
        if notification_already_sent(key):
            continue
        did_send = await send_chore_message(chore, prefix, iso_year, iso_week)
        mark_notification_sent(key)
        if did_send:
            sent += 1

    return web.json_response({"ok": True, "sent": sent, "local_time": now.isoformat()})



async def polling_scheduler_loop():
    """
    Фоновый планировщик для режима polling (локально и на Bothost).
    Проверяет расписание раз в 30 секунд и отправляет напоминания
    только один раз на каждый слот благодаря sent_notifications.
    """
    while True:
        now = datetime.now(TZ)
        iso = now.isocalendar()
        iso_year, iso_week = iso.year, iso.week

        schedule = get_current_reminder_window(now)

        if schedule:
            slug, prefix = schedule

            for chore in ("floor", "bathroom"):
                if not chore_due(chore):
                    continue

                key = f"{iso_year}-W{iso_week}-{slug}-{chore}"
                if notification_already_sent(key):
                    continue

                did_send = await send_chore_message(
                    chore,
                    prefix,
                    iso_year,
                    iso_week,
                )
                mark_notification_sent(key)

                if did_send:
                    print(
                        f"[scheduler] sent {chore}: "
                        f"{iso_year}-W{iso_week} {slug}"
                    )

        await asyncio.sleep(1800)

async def on_startup(app):
    init_db()
    if LOCAL_MODE:
        return
    if not WEBHOOK_BASE_URL:
        raise RuntimeError("WEBHOOK_BASE_URL is required when LOCAL_MODE=false")
    webhook_url = f"{WEBHOOK_BASE_URL}/telegram/webhook"
    await bot.set_webhook(
        webhook_url,
        secret_token=WEBHOOK_SECRET,
        allowed_updates=dp.resolve_used_update_types(),
        drop_pending_updates=False,
    )
    print(f"Webhook set: {webhook_url}")


async def on_shutdown(app):
    await bot.session.close()


def create_app():
    app = web.Application()
    app.router.add_get("/", health)
    app.router.add_get("/health", health)
    app.router.add_get("/scheduler", scheduler)

    SimpleRequestHandler(
        dispatcher=dp,
        bot=bot,
        secret_token=WEBHOOK_SECRET,
    ).register(app, path="/telegram/webhook")

    setup_application(app, dp, bot=bot)
    app.on_startup.append(on_startup)
    app.on_shutdown.append(on_shutdown)
    return app


async def run_local():
    init_db()

    scheduler_task = None

    try:
        # На Bothost и локально работаем через long polling.
        # На сервере BOT_PROXY не задаём — соединение с Telegram идёт напрямую.
        await bot.delete_webhook(drop_pending_updates=False)

        scheduler_task = asyncio.create_task(polling_scheduler_loop())

        print("Bot started in polling mode")
        print("Background cleaning scheduler started")

        await dp.start_polling(bot)

    finally:
        if scheduler_task:
            scheduler_task.cancel()
            try:
                await scheduler_task
            except asyncio.CancelledError:
                pass

        await bot.session.close()


if __name__ == "__main__":
    if LOCAL_MODE:
        asyncio.run(run_local())
    else:
        port = int(os.getenv("PORT", "10000"))
        web.run_app(create_app(), host="0.0.0.0", port=port)